const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

export async function analyzeQuery(query) {
  await delay(800);

  const normalizedQuery = query.toLowerCase();

  let task = "single_image_vqa";
  let answer = "The imagery contains features relevant to the requested analysis.";
  let confidence = 0.87;

  if (
    normalizedQuery.includes("change") ||
    normalizedQuery.includes("between") ||
    normalizedQuery.includes("before") ||
    normalizedQuery.includes("after")
  ) {
    task = "multitemporal_change_analysis";
    answer = "The built-up region appears to have increased between the two observations.";
    confidence = 0.91;
  } else if (
    normalizedQuery.includes("describe") ||
    normalizedQuery.includes("scene")
  ) {
    task = "captioning";
    answer =
      "The scene contains a mixture of built-up land, vegetation, and open terrain.";
    confidence = 0.94;
  } else if (
    normalizedQuery.includes("highlight") ||
    normalizedQuery.includes("where") ||
    normalizedQuery.includes("locate")
  ) {
    task = "grounding";
    answer = "The requested region was located in the imagery.";
    confidence = 0.89;
  } else if (
    normalizedQuery.includes("sar") ||
    normalizedQuery.includes("optical")
  ) {
    task = "optical_sar_analysis";
    answer =
      "The optical and SAR observations provide complementary information about the observed surface.";
    confidence = 0.86;
  }

  return {
    task,
    answer,
    confidence,
    evidence: {
      type: "mock",
      description: "Demo evidence generated by the SatQuery mock analysis layer.",
    },
    execution: {
      model: "SatQuery Demo Model",
      workflow: task,
    },
  };
}