const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

export async function analyzeQuery(query) {
  await delay(800);

  const normalizedQuery = query.toLowerCase();

  let task = "single_image_vqa";
  let answer =
    "The imagery contains features relevant to the requested analysis.";
  let confidence = 0.87;

  if (
    normalizedQuery.includes("change") ||
    normalizedQuery.includes("between") ||
    normalizedQuery.includes("before") ||
    normalizedQuery.includes("after")
  ) {
    task = "multitemporal_change_analysis";

    answer =
      "The built-up region appears to have increased between the two observations.";

    confidence = 0.91;
  } else if (
    normalizedQuery.includes("describe") ||
    normalizedQuery.includes("scene")
  ) {
    task = "captioning";

    answer =
      "The scene contains a mixture of built-up land, vegetation, and open terrain.";

    confidence = 0.94;
  } else if (
    normalizedQuery.includes("highlight") ||
    normalizedQuery.includes("where") ||
    normalizedQuery.includes("locate")
  ) {
    task = "grounding";

    answer = "The requested region was located in the imagery.";

    confidence = 0.89;
  } else if (
    normalizedQuery.includes("sar") ||
    normalizedQuery.includes("optical")
  ) {
    task = "optical_sar_analysis";

    answer =
      "The optical and SAR observations provide complementary information about the observed surface.";

    confidence = 0.86;
  }

  const evidence =
    task === "grounding"
      ? {
          type: "visual",
          description: "The requested region was located in the imagery.",
          overlay: {
            type: "bounding_box",
            x: 58,
            y: 35,
            width: 18,
            height: 16,
            label: "BUILT-UP REGION",
          },
        }
      : task === "multitemporal_change_analysis"
        ? {
            type: "temporal",
            description:
              "A change region was detected between the two observations.",
            before: {
              label: "OBSERVATION A",
              date: "Earlier observation",
            },
            after: {
              label: "OBSERVATION B",
              date: "Later observation",
            },
            overlay: {
              type: "change_region",
              x: 52,
              y: 38,
              width: 20,
              height: 17,
              label: "DETECTED CHANGE",
            },
          }
        : task === "optical_sar_analysis"
          ? {
              type: "multimodal",
              description:
                "Optical and SAR observations were analyzed as complementary sources of surface information.",
              modalities: [
                {
                  type: "optical",
                  label: "OPTICAL",
                  description:
                    "Surface appearance and spectral information.",
                },
                {
                  type: "sar",
                  label: "SAR",
                  description:
                    "Radar-based structural and surface response.",
                },
              ],
            }
          : {
              type: "mock",
              description:
                "Demo evidence generated by the SatQuery mock analysis layer.",
              overlay: null,
            };

  return {
    task,
    answer,
    confidence,
    evidence,
    execution: {
      model: "SatQuery Demo Model",
      workflow: task,
    },
  };
}