export function downloadAnalysisReport({
  query,
  task,
  result,
  confidence,
  evidence,
}) {
  const confidencePercentage =
    confidence !== null && confidence !== undefined
      ? `${Math.round(confidence * 100)}%`
      : "Not available";

  const taskLabel = task
    ? task.replaceAll("_", " ").toUpperCase()
    : "ANALYSIS";

  const workflow = result?.execution?.workflow
    ? result.execution.workflow.replaceAll("_", " ")
    : "Not available";

  const model = result?.execution?.model || "Not available";

  const evidenceDescription =
    evidence?.description || "No evidence description available.";

  const report = `
SATQUERY AI
REMOTE-SENSING INTELLIGENCE
========================================

ANALYSIS REPORT
========================================

QUERY
${query || "Not available"}

TASK
${taskLabel}

ANSWER
${result?.answer || "No answer available."}

CONFIDENCE
${confidencePercentage}

WORKFLOW
${workflow}

MODEL
${model}

EVIDENCE
${evidenceDescription}

EVIDENCE SOURCE
${evidence?.type || "Not available"}

========================================
Generated by SatQuery AI
========================================
`;

  const blob = new Blob([report.trim()], {
    type: "text/plain;charset=utf-8",
  });

  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");

  link.href = url;
  link.download = `satquery-analysis-${Date.now()}.txt`;

  document.body.appendChild(link);
  link.click();
  link.remove();

  URL.revokeObjectURL(url);
}